# -*- coding: utf-8 -*-
"""ADS EXP 5-SMOTE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WfC0-7pbM8eESu_WKVKNjZMZYySXTZdH
"""

import pandas as pd
import seaborn as sns

dataset=pd.read_excel('/content/Admission_St.xlsx')

dataset

x=dataset.iloc[:,1:4]

y=dataset.iloc[:,0:1]

y.value_counts()

sns.countplot(x="Admit", data =dataset)

from sklearn.model_selection import train_test_split
 x_train,x_test, y_train,y_test=train_test_split(x,y, test_size=0.3,random_state=0)

len(x_train)
len(y_train)

len(x_test)
len(y_test)

from imblearn.over_sampling import RandomOverSampler
ros =RandomOverSampler()
x_ros,y_ros=ros.fit_resample(x_train, y_train)

len(y_ros)

y_ros.value_counts()

from imblearn.over_sampling import RandomOverSampler
ros =RandomOverSampler()
x_ros,y_ros=ros.fit_resample(x_test, y_test)

len(y_ros)

y_ros.value_counts()

from imblearn.over_sampling import SMOTE

x_smote,y_smote=SMOTE(k_neighbors=3).fit_resample(x_train, y_train)
y_smote.value_counts()