# -*- coding: utf-8 -*-
"""ADS EXP 7-time series MA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156QpJv8KelIJ8bfw8vIvM5BK312fH0_6
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

series = pd.read_csv("/content/airlinepassenger.csv" , header =0, index_col=0)

series.head(20)

series.plot()
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose
data = pd.read_csv(r"/content/airlinepassenger.csv")
data.columns =['date' , 'data']
data['date'] = pd.to_datetime(data['date'])
data = data.set_index('date')
result = seasonal_decompose(data , model='multicaptive')
result.plot()
plt.show()

product = {'month' :[1,2,3,4,5,6,7,8,9,10,11,12] , 'demand' : [290,260,288,300,310,303,329,340,316,330,308 , 310]}

df = pd.DataFrame(product)

df.head()

df['pandas_SMA_3'] = df.iloc[: , 1].rolling(window =3).mean()

df.head()

df['pandas_SMA_4'] = df.iloc[: , 1].rolling(window = 4).mean()

df.head()

plt.figure(figsize =[15 , 10])
plt.grid(True)
plt.plot(df['demand']  , label=['data'])
plt.plot(df['pandas_SMA_3'] , label = 'SMA 3 Months')
plt.plot(df['pandas_SMA_3'] , label = 'SMA 4 Months')
plt.legend(loc=2)

